[package]
name = "bbm-primitives"
edition.workspace = true
version.workspace = true

[dependencies]
thiserror = { workspace = true }
anyhow = { workspace = true }

sha3 = { workspace = true }
hex = { workspace = true }
